const {
  APP_PORT,
  ENVIRONMENT,
  MUX_TOKEN_ID,
  MUX_TOKEN_SECRET,
  LAMBDA_API_KEY,
  MUX_WEBHOOK_SECRET,
  RAZORPAY_KEY_ID,
  RAZORPAY_KEY_SECRET,
} = process.env;

export const ENV = {
  PORT: APP_PORT,
  ENVIRONMENT: ENVIRONMENT,
  MUX_TOKEN_ID: MUX_TOKEN_ID,
  MUX_TOKEN_SECRET: MUX_TOKEN_SECRET,
  LAMBDA_API_KEY: LAMBDA_API_KEY,
  MUX_WEBHOOK_SECRET: MUX_WEBHOOK_SECRET,
  RAZORPAY_KEY_ID: RAZORPAY_KEY_ID,
  RAZORPAY_KEY_SECRET: RAZORPAY_KEY_SECRET,
};

export default () => ({
  envFilePath: process.env.ENVIRONMENT
    ? `.env.${process.env.ENVIRONMENT}`
    : '.env',
});
