  <script>
window.ff={
c:{s:'fieldflicks',p:'https://play.google.com/store/apps/details?id=com.fieldflicks&hl=en_IN',a:'https://apps.apple.com/app/fieldflicks/id1234567890',d:4000},
o:false,r:'',
l:function(m,d){console.log('[FF]',m,d||'');const x=document.getElementById('ff-d');if(x){x.innerHTML+=`<div style="margin:1px 0;font-size:10px;">${new Date().toLocaleTimeString()}: ${m}</div>`;x.scrollTop=x.scrollHeight;}},
g:function(){const u=new URLSearchParams(window.location.search);const p=window.location.pathname.split('/');const i=u.get('id')||u.get('recordingId')||(p.includes('shared-recording')?p[p.indexOf('shared-recording')+1]:null);this.r=i||'demo';this.l('ID: '+this.r);return this.r;},
k:function(){const h=window.location.search.includes('id=')||window.location.search.includes('recordingId=');const p=window.location.pathname.includes('shared-recording');this.l('Check',`P:${h} T:${p}`);return h||p;},
s:function(){const h=`<div id="ff-load" style="position:fixed;top:0;left:0;width:100%;height:100%;background:linear-gradient(135deg,#1e3c72 0%,#2a5298 100%);color:white;display:flex;flex-direction:column;justify-content:center;align-items:center;font-family:-apple-system,sans-serif;z-index:999999;"><div style="width:70px;height:70px;background:white;border-radius:12px;display:flex;align-items:center;justify-content:center;font-size:20px;margin-bottom:25px;"><span style="color:#1e3c72;">⚽📱</span></div><div style="width:40px;height:40px;border:2px solid rgba(255,255,255,0.3);border-radius:50%;border-top:2px solid white;animation:spin 1s linear infinite;margin-bottom:15px;"></div><h2 style="font-size:20px;margin:0 0 8px 0;">Opening FieldFlicks...</h2><p style="font-size:12px;opacity:0.8;margin-bottom:10px;">ID: ${this.r}</p><div id="ff-d" style="font-size:9px;opacity:0.7;max-width:280px;max-height:120px;overflow:auto;padding:8px;background:rgba(0,0,0,0.2);border-radius:6px;text-align:left;"></div></div><style>@keyframes spin{0%{transform:rotate(0deg)}100%{transform:rotate(360deg)}}body>*:not(#ff-load){display:none!important}</style>`;document.body.insertAdjacentHTML('beforeend',h);this.l('Screen shown: '+this.r);},
t:function(){this.l('Opening app...');const d=`${this.c.s}://shared-recording/${this.r}`;this.l('Link: '+d);try{window.location.href=d;}catch(e){this.l('Direct failed: '+e.message);}setTimeout(()=>{if(!this.o){this.l('Trying iframe...');try{const i=document.createElement('iframe');i.style.display='none';i.src=d;document.body.appendChild(i);setTimeout(()=>{if(document.body.contains(i)){document.body.removeChild(i);}},1500);}catch(e){this.l('Iframe failed: '+e.message);}}},600);setTimeout(()=>{if(!this.o){this.l('Trying click...');try{const a=document.createElement('a');a.href=d;a.style.display='none';document.body.appendChild(a);a.click();document.body.removeChild(a);}catch(e){this.l('Click failed: '+e.message);}}},1000);},
x:function(){if(this.o){this.l('App opened, not redirecting');return;}this.l('Redirecting to store...');const dt=navigator.userAgent.toLowerCase().includes('iphone')?'ios':'android';const su=dt==='ios'?this.c.a:this.c.p;this.l('Device: '+dt);setTimeout(()=>{window.location.href=su;},400);},
h:function(){this.l('=== Starting ===');this.l('URL: '+window.location.href);if(!this.k()){this.l('Not shared URL');return;}this.g();this.l('Proceeding with: '+this.r);this.s();setTimeout(()=>{this.t();},800);setTimeout(()=>{this.x();},this.c.d);},
i:function(){const self=this;this.l('Init...');document.addEventListener('visibilitychange',function(){if(document.hidden){self.l('*** App opened! ***');self.o=true;}});window.addEventListener('blur',function(){self.l('*** Blur - app opened! ***');self.o=true;});setTimeout(()=>{self.h();},100);}
};
window.ff.i();
</script>